### PR TITLE
Applying the changes from the citizen.h file to other files using it

### PR DESCRIPTION
**Pull request by rukouuuu**
Kindly check the changes i have made to the other files

### CODE REVIEW

**Comment by Jeyah-05** [comment]
There seems to be an issue on the other affected files. Kindly change it too

**Review by Jeyah-05 — CHANGES_REQUESTED** [review]
There seems to be an issue on the other affected files. Kindly change it too. Thank you.

**Comment by rukouuuu** [comment]
Kindly check again the changes i have done. Thanks

**Review by Jeyah-05 — APPROVED** [review]
All checks have passed the test. Good job

**Pull request merged**
